import { motion , useScroll} from "motion/react"

function App() {

  const {scrollYProgress} = useScroll();
  console.log(scrollYProgress);
  return (
    <div className='bg-gray-900 h-[100%] w-[100vw] relative'>

      <motion.div 
      
      style={{
        scaleX:scrollYProgress,
      }}
      className='bg-red-500 w-full origin-left fixed h-4  top-0 left-0'></motion.div>
      <div  
    className=' text-center text-white font-mono mr-14 ml-14'>
      <h1 className='text-5xl font-bold pt-7 mb-8'>{import.meta.env.VITE_API_KEY}</h1>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Mollitia praesentium dolores dolorem eum quia iure? Reprehenderit commodi itaque nihil voluptas sunt sed at possimus voluptate nobis, perferendis a corrupti id similique quam eius magnam debitis aspernatur excepturi earum quaerat ipsam dolores soluta dicta! Soluta beatae corrupti natus deleniti praesentium vero, commodi, odit facere amet cumque doloribus nobis voluptas quia, molestiae magni quisquam cum distinctio ipsam sint sapiente nemo veritatis quasi. Illo obcaecati tempore accusantium explicabo eaque aut! Cumque asperiores hic nisi at voluptate! Labore ab tenetur omnis esse similique quia incidunt ipsa accusamus minus temporibus corrupti perspiciatis corporis hic, quaerat mollitia dolore! Voluptates sed suscipit quas dicta officia, ea adipisci iusto, rerum unde ipsam repellendus quod quam amet vel autem assumenda cupiditate sequi consequatur vitae praesentium dolor facilis error nisi magni. Possimus, sequi, doloremque tempora suscipit tempore necessitatibus commodi unde eligendi illum accusantium exercitationem deleniti pariatur perferendis odit rerum. Voluptates, nulla excepturi. Cupiditate, doloremque! Deserunt quia quis cumque quaerat labore magni asperiores accusantium repudiandae vero sunt ducimus beatae, dicta autem molestias, optio eum. Cumque quidem enim, cupiditate, asperiores a fugit odio praesentium ut quas eius dignissimos dolorem omnis veritatis sequi hic, voluptatibus vero nemo eos! Atque illo reiciendis praesentium soluta.</p><br /><br />
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Mollitia praesentium dolores dolorem eum quia iure? Reprehenderit commodi itaque nihil voluptas sunt sed at possimus voluptate nobis, perferendis a corrupti id similique quam eius magnam debitis aspernatur excepturi earum quaerat ipsam dolores soluta dicta! Soluta beatae corrupti natus deleniti praesentium vero, commodi, odit facere amet cumque doloribus nobis voluptas quia, molestiae magni quisquam cum distinctio ipsam sint sapiente nemo veritatis quasi. Illo obcaecati tempore accusantium explicabo eaque aut! Cumque asperiores hic nisi at voluptate! Labore ab tenetur omnis esse similique quia incidunt ipsa accusamus minus temporibus corrupti perspiciatis corporis hic, quaerat mollitia dolore! Voluptates sed suscipit quas dicta officia, ea adipisci iusto, rerum unde ipsam repellendus quod quam amet vel autem assumenda cupiditate sequi consequatur vitae praesentium dolor facilis error nisi magni. Possimus, sequi, doloremque tempora suscipit tempore necessitatibus commodi unde eligendi illum accusantium exercitationem deleniti pariatur perferendis odit rerum. Voluptates, nulla excepturi. Cupiditate, doloremque! Deserunt quia quis cumque quaerat labore magni asperiores accusantium repudiandae vero sunt ducimus beatae, dicta autem molestias, optio eum. Cumque quidem enim, cupiditate, asperiores a fugit odio praesentium ut quas eius dignissimos dolorem omnis veritatis sequi hic, voluptatibus vero nemo eos! Atque illo reiciendis praesentium soluta.</p><br /><br />
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Mollitia praesentium dolores dolorem eum quia iure? Reprehenderit commodi itaque nihil voluptas sunt sed at possimus voluptate nobis, perferendis a corrupti id similique quam eius magnam debitis aspernatur excepturi earum quaerat ipsam dolores soluta dicta! Soluta beatae corrupti natus deleniti praesentium vero, commodi, odit facere amet cumque doloribus nobis voluptas quia, molestiae magni quisquam cum distinctio ipsam sint sapiente nemo veritatis quasi. Illo obcaecati tempore accusantium explicabo eaque aut! Cumque asperiores hic nisi at voluptate! Labore ab tenetur omnis esse similique quia incidunt ipsa accusamus minus temporibus corrupti perspiciatis corporis hic, quaerat mollitia dolore! Voluptates sed suscipit quas dicta officia, ea adipisci iusto, rerum unde ipsam repellendus quod quam amet vel autem assumenda cupiditate sequi consequatur vitae praesentium dolor facilis error nisi magni. Possimus, sequi, doloremque tempora suscipit tempore necessitatibus commodi unde eligendi illum accusantium exercitationem deleniti pariatur perferendis odit rerum. Voluptates, nulla excepturi. Cupiditate, doloremque! Deserunt quia quis cumque quaerat labore magni asperiores accusantium repudiandae vero sunt ducimus beatae, dicta autem molestias, optio eum. Cumque quidem enim, cupiditate, asperiores a fugit odio praesentium ut quas eius dignissimos dolorem omnis veritatis sequi hic, voluptatibus vero nemo eos! Atque illo reiciendis praesentium soluta.</p><br /><br />
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Mollitia praesentium dolores dolorem eum quia iure? Reprehenderit commodi itaque nihil voluptas sunt sed at possimus voluptate nobis, perferendis a corrupti id similique quam eius magnam debitis aspernatur excepturi earum quaerat ipsam dolores soluta dicta! Soluta beatae corrupti natus deleniti praesentium vero, commodi, odit facere amet cumque doloribus nobis voluptas quia, molestiae magni quisquam cum distinctio ipsam sint sapiente nemo veritatis quasi. Illo obcaecati tempore accusantium explicabo eaque aut! Cumque asperiores hic nisi at voluptate! Labore ab tenetur omnis esse similique quia incidunt ipsa accusamus minus temporibus corrupti perspiciatis corporis hic, quaerat mollitia dolore! Voluptates sed suscipit quas dicta officia, ea adipisci iusto, rerum unde ipsam repellendus quod quam amet vel autem assumenda cupiditate sequi consequatur vitae praesentium dolor facilis error nisi magni. Possimus, sequi, doloremque tempora suscipit tempore necessitatibus commodi unde eligendi illum accusantium exercitationem deleniti pariatur perferendis odit rerum. Voluptates, nulla excepturi. Cupiditate, doloremque! Deserunt quia quis cumque quaerat labore magni asperiores accusantium repudiandae vero sunt ducimus beatae, dicta autem molestias, optio eum. Cumque quidem enim, cupiditate, asperiores a fugit odio praesentium ut quas eius dignissimos dolorem omnis veritatis sequi hic, voluptatibus vero nemo eos! Atque illo reiciendis praesentium soluta.</p><br /><br />
    </div>
    </div>
  )
}

export default App
